apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: {{.Release.Name}}
  labels:
    app: caddy
    
    
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      # imagePullSecrets:
      #   - name: intersystems-container-registry-secret
      imagePullSecrets:
          {{- if .Values.requiredSecrets.intersystemsContainerRegistrySecret }}    
          - name: {{ .Values.requiredSecrets.intersystemsContainerRegistrySecret }}
          {{- end }}
      containers:
        - name: sds-caddy
          # image: containers.intersystems.com/iscinternal/sds-service/sds-caddy:0.1.0
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources:
            requests:
              cpu: {{ .Values.compute.database.cpu }}
              memory: {{ .Values.compute.database.memory }}
          ports:
            - name: management
              containerPort: 8000
            - name: quickfix
              containerPort: 3001
      {{- if .Values.compute.database.nodeTypeSelector }}
      nodeSelector:
        sds/node-type: {{ .Values.compute.database.nodeTypeSelector }}
      {{- end }}
      tolerations:
      - key: sds/select-worker
        value: select-worker
        effect: NoSchedule
